### ISSUE TITLE
启动时异常~

### ISSUE THREAD

**Issue by lyman-meng** [hongyaohongyao/SmartClassroomJava#1]
sppe:file:/C:/Users/pc01/Desktop/SmartClassroomJava-master_new/SmartClassroomJava-master/target/classes/sppe
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ai.djl.engine.EngineException: Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\RegisterCPU.cpp:5925 [kernel]
BackendSelect: registered at aten\src\ATen\RegisterBackendSelect.cpp:596 [kernel]
Named: registered at ..\..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradCPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradCUDA: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradXLA: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradNestedTensor: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradPrivateUse1: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradPrivateUse2: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradPrivateUse3: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
Tracer: registered at ..\..\torch\csrc\autograd\generated\TraceType_0.cpp:10499 [kernel]
Autocast: fallthrough registered at ..\..\aten\src\ATen\autocast_mode.cpp:250 [backend fallback]
Batched: registered at ..\..\aten\src\ATen\BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ..\..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]

============================Close: xyz.hyhy.scai.exemodules.YoloModule@d6b43de
	at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
	at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1359)
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:85)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:156)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:174)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:99)
	at xyz.hyhy.scai.ml.YoloV5Detector.<init>(YoloV5Detector.java:46)
	at xyz.hyhy.scai.exemodules.YoloModule.open(YoloModule.java:25)
	at xyz.hyhy.scai.core.modules.BaseModule.run(BaseModule.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ai.djl.engine.EngineException: Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\RegisterCPU.cpp:5925 [kernel]
BackendSelect: registered at aten\src\ATen\RegisterBackendSelect.cpp:596 [kernel]
Named: registered at ..\..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradCPU: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradCUDA: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradXLA: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradNestedTensor: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradPrivateUse1: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradPrivateUse2: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
AutogradPrivateUse3: registered at ..\..\torch\csrc\autograd\generated\VariableType_0.cpp:9273 [autograd kernel]
Tracer: registered at ..\..\torch\csrc\autograd\generated\TraceType_0.cpp:10499 [kernel]
Autocast: fallthrough registered at ..\..\aten\src\ATen\autocast_mode.cpp:250 [backend fallback]
Batched: registered at ..\..\aten\src\ATen\BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ..\..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]

	at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
	at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1359)
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:85)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:156)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:174)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:99)
	at xyz.hyhy.scai.ml.ParallelPoseEstimator.<init>(ParallelPoseEstimator.java:114)
	at xyz.hyhy.scai.ml.AlphaPoseEstimator.<init>(AlphaPoseEstimator.java:24)
	at xyz.hyhy.scai.exemodules.AlphaPoseModule.open(AlphaPoseModule.java:27)
	at xyz.hyhy.scai.core.modules.BaseModule.run(BaseModule.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
============================Close: xyz.hyhy.scai.exemodules.AlphaPoseModule@6870323
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688
process: 0, wait: 0, name: xyz.hyhy.scai.startmodules.VideoModule@23157688

**Comment by 0xiyangyang0** [comment]
+1请问怎么解决

**Comment by xingxing-zhu** [comment]
项目中添加了 SLF4J 适配器的具体实现,例如
`<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.6</version>  
</dependency>
`
